mrSheploo additions
HeroGamers/DiscordGods pull request #2
Opened 2021-06-22 09:04 UTC by mrSheploo

Take a look if everything is ok, please.
Added lines to code:

botutils.py
Lines 79-84 & 133-134

GodManager.py
Lines 171-178

AdminManager.py
Lines 147-154

BotManager.py
Lines 49-51

database.py
Lines 181-184

2021-06-22 18:13 UTC, HeroGamers requested changes
You have copied all of the cogs to the root directory?
Please make changes to the actual files instead of creating duplicate files, as the bot won't run with this structure.

2021-06-22 19:31 UTC, mrSheploo commented
I tried to make all files to be in their own directiories. Well like I said
it was my first time using github.

I tried pushing my edits via github desctop app using git push command.
However then it crashes. I'll try doing it again tomorow (10:30pm now here)
in a proper way.

2021-06-22, an 21:13, Hero ***@***.***> rašė:

> *@HeroGamers* requested changes on this pull request.
>
> You have copied all of the cogs to the root directory?
> Please make changes to the actual files instead of creating duplicate
> files, as the bot won't run with this structure.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HeroGamers/DiscordGods/pull/2#pullrequestreview-689851787>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUCCDSQEJAOYWDYQDZINEFLTUDHFLANCNFSM47DHYTUQ>
> .
>

2021-06-22 19:40 UTC, HeroGamers commented
Take your time! Thanks for the work!

2021-06-24 15:31 UTC, mrSheploo commented
Hi again!
I hope that I managed to put all the files into their original directories.
Hope it works ;)

2021-06-26 21:37 UTC, HeroGamers requested changes
I have requested a few changes, but other than that, it looks like a decent first commit!
Good job~

2021-06-26 21:37 UTC, HeroGamers commented on database.py
> +    query =gods.update(Name=name).where(gods.ID == godid)
No parameter called name, you called it godname.

2021-06-26 21:37 UTC, HeroGamers commented on cogs/GodManager.py
> +    @commands.command(name="rename", aliases=["rn"]) #My attempt to make a possibility to change god's name (mrSheploo)
Remove your name from this line - people can see that you made it by looking at the commit history.

2021-06-26 21:37 UTC, HeroGamers commented on cogs/GodManager.py
> +
Please also ensure that there is no other God with that name already, by using the getGodName function in the database.
See the create command in GodManager (https://github.com/HeroGamers/DiscordGods/blob/master/cogs/GodManager.py#L30).

2021-06-26 21:37 UTC, HeroGamers commented on cogs/AdminManager.py
> +    async def _rename(self, ctx, arg1):
Call it the same name as the name argument on the command (forcerename) for consistency.

2021-06-26 21:37 UTC, HeroGamers commented on cogs/AdminManager.py
> +
Ensure that there is no other God with that name already, by using the getGodName function in the database.
See the create command in GodManager (https://github.com/HeroGamers/DiscordGods/blob/master/cogs/GodManager.py#L30).

2021-06-26 21:37 UTC, HeroGamers commented on cogs/AdminManager.py
> +    @commands.command(name="forcerename", aliases=["frn"]) #My attempt to make a possibility to change god's name (mrSheploo)
Remove name - can be seen in commit history.

2021-06-26 21:37 UTC, HeroGamers commented on Util/botutils.py
> +                ("SACRIFICE", discord.Color.red()), #Added by mrSheploo
Remove your name - can be seen in commit history.

2021-06-26 21:37 UTC, HeroGamers commented on Util/botutils.py
> +            elif god.Gender.upper() == "Machine".upper(): #added by mrSheploo
Remove your name - can be seen in commit history.

2021-06-26 21:37 UTC, HeroGamers commented on cogs/GodManager.py
> +        god = database.getBeliever(ctx.authos.id, ctx.guild.id).God
You accidentally typed authos instead of author (ctx.authos.id -> ctx.author.id).

2021-06-29 21:02 UTC, HeroGamers requested changes
Almost there, just a few things now!
You'd probably want to look into using a dedicated IDE, like PyCharm or Visual Studio Code with Pylint installed.

You're starting to get the hang of it. Lmk if you have any further questions on Discord or just comment here.

2021-06-29 21:02 UTC, HeroGamers commented on cogs/AdminManager.py
> +            return
You accidentally switched the two args around here.

2021-06-29 21:02 UTC, HeroGamers commented on cogs/GodManager.py
> +        if len(args[0]) > 16:
args doesn't exist here. You have only provided the arg1 argument.

2021-07-29 15:52 UTC, mrSheploo commented
Been very busy in a past month due to new job.
I hope I fixed what You've mentioned.
Also, yes, I'll deffinately try dedicated IDE

2023-07-08 13:51 UTC, HeroGamers commented
Closing PR as it's stale.

2023-07-08 13:51 UTC, closed without merging